#!/bin/sh /etc/rc.common
#
# BeeeOn Project 2016
# Author: Matej Postolka <xposto02@stud.fit.vutbr.cz>
# Last modified: 2016-04-04
#

USE_PROCD=1
START=80
APP=beeeon-gateway
BINARY_PATH=/usr/bin
CONFIG_PATH=/usr/etc/beeeon/gateway

registerIniFiles() {
	for f in $(ls $CONFIG_PATH/*.ini $CONFIG_PATH/config.d/*.ini $CONFIG_PATH/config.d/*.xml); do
		procd_set_param file "$f"
	done
}

start_service() {
	mkdir -p /var/run/beeeon/gateway

	procd_open_instance
	procd_set_param command ${BINARY_PATH}/${APP} --config=${CONFIG_PATH}/gateway-startup.ini
	registerIniFiles()
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_close_instance
}
