#include "vpt/VPTZoneModuleType.h"

using namespace BeeeOn;

EnumHelper<VPTZoneModuleTypeEnum::Raw>::ValueMap
&VPTZoneModuleTypeEnum::valueMap()
{
	static EnumHelper<VPTZoneModuleTypeEnum::Raw>::ValueMap valueMap = {
		{MOD_BOILER_OPERATION_TYPE, "MOD_BOILER_OPERATION_TYPE"},
		{MOD_BOILER_OPERATION_MODE, "MOD_BOILER_OPERATION_MODE"},
		{MOD_REQUESTED_ROOM_TEMPERATURE, "MOD_REQUESTED_ROOM_TEMPERATURE"},
		{MOD_CURRENT_ROOM_TEMPERATURE, "MOD_CURRENT_ROOM_TEMPERATURE"},
		{MOD_REQUESTED_WATER_TEMPERATURE_SET, "MOD_REQUESTED_WATER_TEMPERATURE_SET"},
		{MOD_CURRENT_WATER_TEMPERATURE, "MOD_CURRENT_WATER_TEMPERATURE"},
		{MANUAL_REQUESTED_ROOM_TEMPERATURE, "MANUAL_REQUESTED_ROOM_TEMPERATURE"},
		{MANUAL_REQUESTED_WATER_TEMPERATURE, "MANUAL_REQUESTED_WATER_TEMPERATURE"},
		{MANUAL_REQUESTED_TUV_TEMPERATURE, "MANUAL_REQUESTED_TUV_TEMPERATURE"},
		{MOD_REQUESTED_WATER_TEMPERATURE_READ, "MOD_REQUESTED_WATER_TEMPERATURE_READ"},
	};

	return valueMap;
}
