#pragma once

#include "util/Enum.h"

namespace BeeeOn {

class VPTZoneModuleTypeEnum {
public:
	enum Raw {
		MOD_BOILER_OPERATION_TYPE = 0,
		MOD_BOILER_OPERATION_MODE,
		MOD_REQUESTED_ROOM_TEMPERATURE,
		MOD_CURRENT_ROOM_TEMPERATURE,
		MOD_REQUESTED_WATER_TEMPERATURE_SET,
		MOD_CURRENT_WATER_TEMPERATURE,
		MANUAL_REQUESTED_ROOM_TEMPERATURE,
		MANUAL_REQUESTED_WATER_TEMPERATURE,
		MANUAL_REQUESTED_TUV_TEMPERATURE,
		MOD_REQUESTED_WATER_TEMPERATURE_READ,
	};

	static EnumHelper<Raw>::ValueMap &valueMap();
};

typedef Enum<VPTZoneModuleTypeEnum> VPTZoneModuleType;

}
