#ifndef _UR_FIELDS_H_
#define _UR_FIELDS_H_

/************* THIS IS AUTOMATICALLY GENERATED FILE, DO NOT EDIT *************/
#include <unirec/unirec.h>

#define F_ACK_COUNT   0
#define F_ACK_COUNT_T   double
#define F_ACK_WAITING   1
#define F_ACK_WAITING_T   double
#define F_ACL_MTU   2
#define F_ACL_MTU_T   double
#define F_ACL_PACKETS   3
#define F_ACL_PACKETS_T   double
#define F_ADDRESS   4
#define F_ADDRESS_T   double
#define F_AVERAGE   5
#define F_AVERAGE_T   double
#define F_AVERAGE_REQUEST_RTT   6
#define F_AVERAGE_REQUEST_RTT_T   double
#define F_AVERAGE_RESPONSE_RTT   7
#define F_AVERAGE_RESPONSE_RTT_T   double
#define F_BAD_CHECKSUM   8
#define F_BAD_CHECKSUM_T   double
#define F_BAD_ROUTES   9
#define F_BAD_ROUTES_T   double
#define F_BROADCAST_READ_COUNT   10
#define F_BROADCAST_READ_COUNT_T   double
#define F_BROADCAST_WRITE_COUNT   11
#define F_BROADCAST_WRITE_COUNT_T   double
#define F_BYTE   12
#define F_BYTE_T   double
#define F_CALLBACKS   13
#define F_CALLBACKS_T   double
#define F_CAN_COUNT   14
#define F_CAN_COUNT_T   double
#define F_CMDCLASS   15
#define F_CMDCLASS_T   double
#define F_DEV_ADDR   16
#define F_DEV_ADDR_T   uint64_t
#define F_DROPPED   17
#define F_DROPPED_T   double
#define F_EVENT_TYPE   18
#define F_EVENT_TYPE_T   double
#define F_GENRE   19
#define F_GENRE_T   double
#define F_GW_ID   20
#define F_GW_ID_T   double
#define F_HOME_ID   21
#define F_HOME_ID_T   double
#define F_INDEX   22
#define F_INDEX_T   double
#define F_INSTANCE   23
#define F_INSTANCE_T   double
#define F_LAST_REQUEST_RTT   24
#define F_LAST_REQUEST_RTT_T   double
#define F_LAST_RESPONSE_RTT   25
#define F_LAST_RESPONSE_RTT_T   double
#define F_MESSAGE_TYPE   26
#define F_MESSAGE_TYPE_T   double
#define F_NAK_COUNT   27
#define F_NAK_COUNT_T   double
#define F_NET_BUSY   28
#define F_NET_BUSY_T   double
#define F_NO_ACK   29
#define F_NO_ACK_T   double
#define F_NODE_ID   30
#define F_NODE_ID_T   double
#define F_NON_DELIVERY   31
#define F_NON_DELIVERY_T   double
#define F_NOT_IDLE   32
#define F_NOT_IDLE_T   double
#define F_OOF_COUNT   33
#define F_OOF_COUNT_T   double
#define F_QUALITY   34
#define F_QUALITY_T   double
#define F_READ_ABORTS   35
#define F_READ_ABORTS_T   double
#define F_READ_COUNT   36
#define F_READ_COUNT_T   double
#define F_RECEIVED_COUNT   37
#define F_RECEIVED_COUNT_T   double
#define F_RECEIVE_DUPLICATIONS   38
#define F_RECEIVE_DUPLICATIONS_T   double
#define F_RECEIVE_UNSOLICITED   39
#define F_RECEIVE_UNSOLICITED_T   double
#define F_RETRIES   40
#define F_RETRIES_T   double
#define F_ROUTED_BUSY   41
#define F_ROUTED_BUSY_T   double
#define F_RSSI   42
#define F_RSSI_T   double
#define F_RX_ACLS   43
#define F_RX_ACLS_T   double
#define F_RX_BYTES   44
#define F_RX_BYTES_T   double
#define F_RX_ERRORS   45
#define F_RX_ERRORS_T   double
#define F_RX_EVENTS   46
#define F_RX_EVENTS_T   double
#define F_RX_SCOS   47
#define F_RX_SCOS_T   double
#define F_SCO_MTU   48
#define F_SCO_MTU_T   double
#define F_SCO_PACKETS   49
#define F_SCO_PACKETS_T   double
#define F_SENT_COUNT   50
#define F_SENT_COUNT_T   double
#define F_SENT_FAILED   51
#define F_SENT_FAILED_T   double
#define F_SIZE   52
#define F_SIZE_T   double
#define F_SOF_COUNT   53
#define F_SOF_COUNT_T   double
#define F_TIME   54
#define F_TIME_T   ur_time_t
#define F_TX_ACLS   55
#define F_TX_ACLS_T   double
#define F_TX_BYTES   56
#define F_TX_BYTES_T   double
#define F_TX_CMDS   57
#define F_TX_CMDS_T   double
#define F_TX_ERRORS   58
#define F_TX_ERRORS_T   double
#define F_TX_SCOS   59
#define F_TX_SCOS_T   double
#define F_TYPE   60
#define F_TYPE_T   double
#define F_VALUE   61
#define F_VALUE_T   double
#define F_WRITE_COUNT   62
#define F_WRITE_COUNT_T   double
#define F_CHANNELS   63
#define F_CHANNELS_T   char
#define F_CMD   64
#define F_CMD_T   char
#define F_EVENT   65
#define F_EVENT_T   char
#define F_MSG_TYPE   66
#define F_MSG_TYPE_T   char
#define F_PAYLOAD   67
#define F_PAYLOAD_T   char
#define F_PROT_STATE   68
#define F_PROT_STATE_T   char

extern uint16_t ur_last_id;
extern ur_static_field_specs_t UR_FIELD_SPECS_STATIC;
extern ur_field_specs_t ur_field_specs;

#endif

