#ifndef _UR_FIELDS_H_
#define _UR_FIELDS_H_

/************* THIS IS AUTOMATICALLY GENERATED FILE, DO NOT EDIT *************/
#include <unirec/unirec.h>

#define F_ACKCount   0
#define F_ACKCount_T   double
#define F_ACKWaiting   1
#define F_ACKWaiting_T   double
#define F_aclMtu   2
#define F_aclMtu_T   double
#define F_aclPackets   3
#define F_aclPackets_T   double
#define F_address   4
#define F_address_T   double
#define F_average   5
#define F_average_T   double
#define F_averageRequestRTT   6
#define F_averageRequestRTT_T   double
#define F_averageResponseRTT   7
#define F_averageResponseRTT_T   double
#define F_badChecksum   8
#define F_badChecksum_T   double
#define F_badroutes   9
#define F_badroutes_T   double
#define F_broadcastReadCount   10
#define F_broadcastReadCount_T   double
#define F_broadcastWriteCount   11
#define F_broadcastWriteCount_T   double
#define F_callbacks   12
#define F_callbacks_T   double
#define F_CANCount   13
#define F_CANCount_T   double
#define F_dropped   14
#define F_dropped_T   double
#define F_err_value   15
#define F_err_value_T   double
#define F_GW_ID   16
#define F_GW_ID_T   uint64_t
#define F_ID   17
#define F_ID_T   uint64_t
#define F_lastRequestRTT   18
#define F_lastRequestRTT_T   double
#define F_lastResponseRTT   19
#define F_lastResponseRTT_T   double
#define F_moving_average   20
#define F_moving_average_T   double
#define F_moving_median   21
#define F_moving_median_T   double
#define F_moving_variance   22
#define F_moving_variance_T   double
#define F_NAKCount   23
#define F_NAKCount_T   double
#define F_netBusy   24
#define F_netBusy_T   double
#define F_noACK   25
#define F_noACK_T   double
#define F_nodeID   26
#define F_nodeID_T   double
#define F_nonDelivery   27
#define F_nonDelivery_T   double
#define F_notIdle   28
#define F_notIdle_T   double
#define F_OOFCount   29
#define F_OOFCount_T   double
#define F_profile_value   30
#define F_profile_value_T   double
#define F_quality   31
#define F_quality_T   double
#define F_readAborts   32
#define F_readAborts_T   double
#define F_readCount   33
#define F_readCount_T   double
#define F_receivedCount   34
#define F_receivedCount_T   double
#define F_receiveDuplications   35
#define F_receiveDuplications_T   double
#define F_receiveUnsolicited   36
#define F_receiveUnsolicited_T   double
#define F_retries   37
#define F_retries_T   double
#define F_routedBusy   38
#define F_routedBusy_T   double
#define F_rxAcls   39
#define F_rxAcls_T   double
#define F_rxBytes   40
#define F_rxBytes_T   double
#define F_rxErrors   41
#define F_rxErrors_T   double
#define F_rxEvents   42
#define F_rxEvents_T   double
#define F_rxScos   43
#define F_rxScos_T   double
#define F_scoMtu   44
#define F_scoMtu_T   double
#define F_scoPackets   45
#define F_scoPackets_T   double
#define F_sentCount   46
#define F_sentCount_T   double
#define F_sentFailed   47
#define F_sentFailed_T   double
#define F_SOFCount   48
#define F_SOFCount_T   double
#define F_TIME   49
#define F_TIME_T   double
#define F_txAcls   50
#define F_txAcls_T   double
#define F_txBytes   51
#define F_txBytes_T   double
#define F_txCmds   52
#define F_txCmds_T   double
#define F_txErrors   53
#define F_txErrors_T   double
#define F_txScos   54
#define F_txScos_T   double
#define F_VALUE   55
#define F_VALUE_T   double
#define F_writeCount   56
#define F_writeCount_T   double
#define F_alert_desc   57
#define F_alert_desc_T   char
#define F_profile_key   58
#define F_profile_key_T   char
#define F_ur_key   59
#define F_ur_key_T   char

extern uint16_t ur_last_id;
extern ur_static_field_specs_t UR_FIELD_SPECS_STATIC;
extern ur_field_specs_t ur_field_specs;

#endif
